# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 167fbc2ae25c4ecb000dcb3fedfa4aabf8b74f3505fe0e2720b391a18189f1e3db8dfe330672e95fd32c3c03173791c70303d399dffb27b827b29c74e75124ee

test:
  secret_key_base: 9e6a152d8988cd2ba23ec4b53a913de9aebba3ed67238208f743242e7580d0991eb39812fbaafc7b3694a5e4182e92fe57788f7c1b8d316fdcbc5e20128dadaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
